name: AE
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - pandas
  - cython
  - cartopy
  - matplotlib
  - h5py
  - notebooks
  - pip
  - pip:
    -cdflib
    - hdf5storage
    - lxml
    - chaosmagpy